apiVersion: v1
kind: ConfigMap
metadata:
  name: makeline-service-configmap
data:  
  ORDER_QUEUE_URI: "{{ .Values.makelineService.orderQueueUri }}"
  ORDER_QUEUE_USERNAME: "{{ .Values.makelineService.orderQueueUsername }}"
  ORDER_QUEUE_PASSWORD: "{{ .Values.makelineService.orderQueuePassword }}"
  ORDER_QUEUE_NAME: "{{ .Values.makelineService.orderQueueName }}"
  ORDER_DB_URI: "{{ .Values.makelineService.orderDBUri }}"
  ORDER_DB_NAME: "{{ .Values.makelineService.orderDBName }}"
  {{- if eq .Values.makelineService.orderDBApi "cosmosdbsql" }}
  ORDER_DB_API: "{{ .Values.makelineService.orderDBApi }}"
  ORDER_DB_CONTAINER_NAME: "{{ .Values.makelineService.orderDBContainerName }}"
  ORDER_DB_PARTITION_KEY: "storeId"
  ORDER_DB_PARTITION_VALUE: "pets"
  {{- else }}
  ORDER_DB_COLLECTION_NAME: "{{ .Values.makelineService.orderDBCollectionName }}"
  {{- end }}
---
{{- if and .Values.makelineService.orderDBUsername .Values.makelineService.orderDBPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: makeline-service-secrets
data:
  ORDER_DB_USERNAME: "{{ .Values.makelineService.orderDBUsername | b64enc  }}"
  ORDER_DB_PASSWORD: "{{ .Values.makelineService.orderDBPassword | b64enc  }}"
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: makeline-service
        image: {{ .Values.makelineService.image.repository }}:{{ .Values.makelineService.image.tag }}
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: makeline-service-configmap
        {{- if and .Values.makelineService.orderDBUsername .Values.makelineService.orderDBPassword }}
        - secretRef:
            name: makeline-service-secrets
        {{- end }}
        resources:
          requests:
            cpu: 1m
            memory: 6Mi
          limits:
            cpu: 5m
            memory: 20Mi
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: makeline-service