apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-configs
data:  
  {{- if eq .Values.useAzureAd true }}
  USE_WORKLOAD_IDENTITY_AUTH: "true"
  {{- else }}
  ORDER_QUEUE_PORT: "{{ .Values.orderService.queuePort }}"
  {{- end }}
  {{- if .Values.orderService.queueTransport }}
  ORDER_QUEUE_TRANSPORT: "{{ .Values.orderService.queueTransport }}"
  {{- end }}
  ORDER_QUEUE_HOSTNAME: "{{ .Values.orderService.queueHost }}"
  ORDER_QUEUE_NAME: "{{ .Values.orderService.queueName }}"
  FASTIFY_ADDRESS: "0.0.0.0"
---
{{- if eq .Values.useAzureAd false }}
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
data:
  ORDER_QUEUE_USERNAME: "{{ .Values.orderService.queueUsername | b64enc }}"
  ORDER_QUEUE_PASSWORD: "{{ .Values.orderService.queuePassword | b64enc }}"
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        {{- if eq .Values.useAzureAd true }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      {{- if eq .Values.useAzureAd true }}
      serviceAccount: {{ .Values.managedIdentityName }}
      {{- end }}
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: order-service
        image: {{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag }}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: order-service-configs
        {{- if eq .Values.useAzureAd false }}
        - secretRef:
            name: order-service-secrets
        {{- end }}
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
      {{- if eq .Values.useRabbitMQ true }}
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: order-service